version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/wordpress
hooks:
  ApplicationRestart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
