version: 0.2
env:
  parameter-store:
    WP_CONFIG: "/amrit/wp-config"
phases:
  install:
    runtime-versions:
        php: 7.4
  pre_build:
    commands:
      - echo Running Pre-Build script...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo $WP_CONFIG > wp-config.php
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
